[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "Tower"
[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "HomeLab"        # whatever you named your org
  bucket = "telegraf"             # the bucket you created
  timeout = "30s"
[[outputs.mqtt]]
  servers = ["tcp://${MQTT_HOST}:1883"]
  topic = "systems/{{.Hostname}}/{{.PluginName}}"
  data_format = "json"
  username = "telegraf"
  password = "${TELEGRAF_MQTT_PASSWORD}"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  core_tags = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
  devices = ["sda","sdb","sdc","sdd","sde","sdf","sdg","sdh","sdi","sdj"]
  skip_serial_number = true
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
  [inputs.net.tagdrop]
    interface = ["veth*", "br-*", "tunl*"]
[[inputs.netstat]]
[[inputs.nstat]]
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "15s"
  container_state_include = ["running"]
[[inputs.linux_sysctl_fs]]
[[inputs.temp]]
[[inputs.conntrack]]
  files = ["ip_conntrack_count","ip_conntrack_max",
           "nf_conntrack_count","nf_conntrack_max"]
  dirs = ["/proc/sys/net/netfilter","/proc/sys/net/ipv4/netfilter"]
[[inputs.interrupts]]
[[inputs.internal]]
  collect_memstats = false
